BUG: Debugging welcome peer for Note 4 issue
AND-303

Debugging welcome peer for Note 4 issue. Also refactored much of Media code into SkylinkMediaService.
Welcome issue seems somewhat better but still not resolved.
EngineIOException exceptions were likely due to time out in trying to contact signaling server.
This was traced to error messages like:
java.net.SocketTimeoutException: failed to connect to sg-signaling.temasys.com.sg/54.169.80.53 (port 443) after 10000ms

Major changes:
- Investigated:
  - Sending "enter" where "welcome" is sent.
  - com.github.nkzawa.engineio.client.EngineIOException: xhr poll error
  - com.github.nkzawa.engineio.client.EngineIOException: xhr post error
  - socketio usage.
- Change obtaining of local media to be independent of connecting to room.
- Re-added some missing locks and changed lock types
  - new lockDisconnectMediaLocal for local media code.
  - Used lockDisconnectMsg for messages.